#!/usr/bin/env python3
"""
Generate the Lua API reference the agent reads before writing scripts.

Extracted from the luaL_Reg tables in cmd/lua.c so it cannot drift from what the
firmware actually exposes -- a stale reference is worse than none, because the
model believes it and writes code that fails.

Run from the repo root after changing any binding:
    python3 tools/gen_lua_api.py
"""
import re
import sys
from pathlib import Path

SRC = Path("breezybox-cardputer/cmd/lua.c")
OUT = Path("packages/espclaw/root/apps/espclaw/lua_api.md")

# Registered outside the s_breezy_* tables.
EXTRA = {"https": ["request"]}

# Signatures worth spelling out, keyed by "module.function".
HINTS = {
    "battery.read_pct":   "() -> 0..100",
    "battery.read_uv":    "() -> microvolts",
    "battery.read_level": "() -> 0..4",
    "read_file":          "(path) -> string",
    "write_file":         "(path, text[, append])",
    "listdir":            "(path) -> table of names",
    "exists":             "(path) -> boolean",
    "exec":               "(command) -> output string",
    "heap":               "() -> free, min_free, largest",
    "write":              "(text)  -- no trailing newline, unlike print()",
    "term_size":          "() -> cols, rows",
    "readkey":            "(timeout_ms) -> char or nil",
    "json.encode":        "(value) -> string",
    "json.decode":        "(string) -> value",
    "storage.sd_mounted": "() -> boolean",
    "network.is_connected": "() -> boolean",
    "network.http_get":   "(url) -> {status=, body=}  -- http:// only",
    "https.request":      "{url=, method=, headers=, body=, on_chunk=} -> status, bytes",
    "gfx.mode":           '("text"|"150p"|"vga13h")',
    "sound.tone":         "(hz, ms)",
    "i2c.scan":           "() -> table of addresses",
    "pin.mode":           '(gpio, "in"|"out")',
}


def main() -> int:
    if not SRC.exists():
        print(f"error: {SRC} not found (run from the repo root)", file=sys.stderr)
        return 1

    src = SRC.read_text()
    mods: dict[str, list[str]] = {}
    for m in re.finditer(r"static const luaL_Reg (s_breezy_\w+)\[\] = \{(.*?)\n\};", src, re.S):
        name = m.group(1).replace("s_breezy_", "").replace("_lib", "")
        mods[name] = re.findall(r'\{\s*"([^"]+)"', m.group(2))
    mods.update(EXTRA)

    if "lib" not in mods:
        print("error: could not find the core breezy table", file=sys.stderr)
        return 1

    lines = [
        "# breezy Lua API",
        "",
        "Generated by tools/gen_lua_api.py from the bindings in cmd/lua.c.",
        "Do not edit by hand; regenerate instead.",
        "",
        "Every script starts with:",
        "",
        "```lua",
        'local breezy = require("breezy")',
        "```",
        "",
        "`breezy` is a module, not a global. There is no `io` or `os` library:",
        "use `print()`, or `breezy.write()` to write without a newline.",
        "",
        "## Core",
        "",
    ]

    for fn in mods.pop("lib"):
        hint = HINTS.get(fn, "")
        lines.append(f"- `breezy.{fn}{hint}`" if hint else f"- `breezy.{fn}()`")

    for mod in sorted(mods):
        lines += ["", f"## breezy.{mod}", ""]
        for fn in mods[mod]:
            key = f"{mod}.{fn}"
            hint = HINTS.get(key, "")
            lines.append(f"- `breezy.{mod}.{fn}{hint}`" if hint
                         else f"- `breezy.{mod}.{fn}()`")

    lines += [
        "",
        "## Hardware",
        "",
        "### Grove port (HY2.0-4P): GND, 5V, G2, G1",
        "",
        "`G1` and `G2` are the only user-free GPIOs, and every other pin below is",
        "already committed to something. Accessories connect here.",
        "",
        "```lua",
        'local breezy = require("breezy")',
        "",
        "-- I2C accessory (most M5Stack Units): SDA=G1, SCL=G2",
        "breezy.i2c.open(1, 2, { freq = 400000 })",
        "for _, addr in ipairs(breezy.i2c.scan()) do",
        '  print(string.format("device at 0x%02X", addr))',
        "end",
        "breezy.i2c.close()",
        "",
        "-- Digital out, e.g. a relay or LED unit on G2",
        'breezy.pin.mode(2, "out")',
        "breezy.pin.write(2, 1)",
        "",
        "-- Digital in, e.g. a button unit on G1",
        'breezy.pin.mode(1, "in")',
        "print(breezy.pin.read(1))",
        "",
        "-- Analog in on G1 (ADC1 channel 0)",
        "print(breezy.adc.read(0))",
        "",
        "-- Serial accessory: TX=G1, RX=G2",
        "local h = breezy.uart.open(1, 115200, 1, 2)",
        'breezy.uart.write(h, "hello\\r\\n")',
        "print(breezy.uart.read(h, 64, 100))",
        "breezy.uart.close(h)",
        "```",
        "",
        "### Pins already in use -- do not drive these",
        "",
        "| Function | Pins |",
        "|---|---|",
        "| LCD (ST7789) | MOSI 35, SCLK 36, CS 37, DC 34, RST 33, backlight 38 |",
        "| microSD | CLK 40, MOSI 14, MISO 39, CS 12 |",
        "| Speaker (I2S) | BCLK 41, WS 43, DOUT 42 |",
        "| Battery sense | GPIO 10 (ADC) |",
        "| Keyboard (v1.1 matrix) | out 8, 9, 11; in 13, 15, 3, 4, 5, 6, 7 |",
        "| Keyboard (ADV, TCA8418) | I2C SDA 8, SCL 9 |",
        "",
        "The keyboard occupies different pins on the two boards, but neither uses",
        "G1 or G2, so Grove accessories work identically on both.",
        "",
        "## Notes",
        "",
        "- Filesystem roots are `/root` (internal flash) and `/sd` (card).",
        "- `breezy.network.http_*` is plain HTTP only; use `breezy.https.request`",
        "  for TLS.",
        "- Graphics calls need `breezy.gfx.mode(...)` first, and `mode(\"text\")`",
        "  afterwards to restore the console.",
        "",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    total = sum(len(v) for v in mods.values()) + len(mods)
    print(f"wrote {OUT} ({total}+ functions)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
